/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always 200 once the process is up; does not check dependencies (see /readyz).
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description 200 only once Postgres and Redis are both reachable.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accrue points for a completed sale (1C webhook)
         * @description Idempotent on (store, transaction_id): a retried request with the same transaction_id and parameters returns the original result (`replayed: true`) rather than crediting points twice. Requires the `transactions.write` scope.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem points at checkout (1C webhook)
         * @description Idempotent on (store, transaction_id), like accrual. Requires the `transactions.write` scope.
         */
        post: operations["redeemTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Partially or fully refund a prior accrual/redeem (1C webhook)
         * @description Idempotent on (store, transaction_id), like accrual/redeem. original_transaction_id/original_transaction_type identify the transaction being reversed; original_transaction_type is only required when original_transaction_id was used for both an accrual and a redeem under this store. Multiple partial refunds against the same original are supported — see refunded_amount_total/ fully_refunded on the response. Requires the `transactions.write` scope.
         */
        post: operations["refundTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/resolve-qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a customer-issued QR payload for a store-scoped client (POS)
         * @description Atomically consumes a one-time QR payload minted by POST /me/qr, resolving (and creating/linking if this is the client's first visit to this store) a store-scoped client. Requires the `clients.lookup` scope. See DEC-011.
         */
        post: operations["resolveQR"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a client by phone (1C/POS)
         * @description Resolves a client_id and current balance for a phone already registered under the requesting store. Requires the `clients.lookup` scope.
         */
        get: operations["lookupClientByPhone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a client's point balance (1C/POS)
         * @description 404s if id doesn't belong to the requesting store. Requires the `balances.read` scope.
         */
        get: operations["getClientBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP code for a phone number
         * @description Always 200 with the same body whether or not phone is already registered — cannot be used to enumerate accounts.
         */
        post: operations["requestOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an OTP code and obtain a session */
        post: operations["verifyOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Presenting an already-rotated refresh token is treated as compromise — every session for that account is revoked.
         */
        post: operations["refreshCustomerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a single session
         * @description Idempotent — an unknown/already-revoked token still returns 204.
         */
        post: operations["customerLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every session for the caller's account */
        post: operations["customerLogoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current customer profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current customer's point balance, per linked store */
        get: operations["getMyBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current customer's transaction history across all linked stores
         * @description Keyset-paginated, newest first.
         */
        get: operations["getMyTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a new one-time QR payload for identification at POS
         * @description The payload carries no PII and is one-time-use (see DEC-011). Re-issuing before the previous QR's issue cooldown elapses returns 429 with Retry-After.
         */
        post: operations["issueQR"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or refresh an FCM push token for the caller's account */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/devices/{deviceID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the caller's own devices
         * @description 404s (not 403) if deviceID belongs to a different account, so the response never confirms the ID exists.
         */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a verified OIDC ID token for a PromoGo staff access token */
        post: operations["staffOIDCLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the caller's own staff profile and memberships
         * @description Returns the caller's profile plus every active membership and its resolved permissions. No organization/store scope applies — this describes the caller, not one tenant's resource. An account with no active membership still gets 200 with an empty `memberships` array.
         */
        get: operations["getStaffMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations visible to the caller
         * @description A platform_admin membership (anywhere) sees every organization; any other caller sees only the organizations of their own active memberships.
         */
        get: operations["listOrganizations"];
        put?: never;
        /**
         * Create an Organization
         * @description Requires the global `organizations.manage` permission (any organization) — a bootstrap operation.
         */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stores visible to the caller within an Organization
         * @description A platform_admin, or a caller with an organization-wide membership in orgID, sees every store in the organization; a caller with only store-scoped membership(s) in orgID sees only those stores. 403 if the caller has no membership in orgID at all.
         */
        get: operations["listStores"];
        put?: never;
        /**
         * Create a Store within an Organization
         * @description Requires `stores.manage` in orgID.
         */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a Store
         * @description Requires `stores.read`. 404s if storeID doesn't belong to orgID.
         */
        get: operations["getStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List staff memberships in an Organization
         * @description Requires `staff.manage`.
         */
        get: operations["listStaffMemberships"];
        put?: never;
        /**
         * Grant a staff membership
         * @description Requires `staff.manage`. Creates the target StaffUser row (by OIDC subject) if it doesn't exist yet — the rest of their profile fills in on their first real OIDC login.
         */
        post: operations["createStaffMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/staff/{membershipID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a staff membership's role or status
         * @description Requires `staff.manage`.
         */
        patch: operations["updateStaffMembership"];
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List clients in a store, paginated
         * @description Requires `clients.read`. Keyset-paginated via `?limit=&cursor=` (cursor is the previous page's last client id). Phone is masked (e.g. "********4567") for a caller whose only membership in this scope is support_viewer. Advanced filters are out of scope for this endpoint until the client-list filter/masking UX decision (Q-P1-070) is made — this is exact pagination only.
         */
        get: operations["adminListClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/clients/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a client by phone (admin view)
         * @description Requires `clients.read`. Phone is masked (e.g. "********4567") for a caller whose only membership in this scope is support_viewer.
         */
        get: operations["adminLookupClient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/clients/{clientID}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a client's transaction history (admin view)
         * @description Requires `transactions.read`. 404s if clientID doesn't belong to storeID.
         */
        get: operations["adminListClientTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/loyalty-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a store's loyalty configuration
         * @description Requires `loyalty_config.read`.
         */
        get: operations["getLoyaltyConfig"];
        /**
         * Set a store's loyalty configuration
         * @description Requires `loyalty_config.write`.
         */
        put: operations["putLoyaltyConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/loyalty-config/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a store's loyalty configuration history
         * @description Requires `loyalty_config.read`. Newest version first — every prior effective configuration, for audit and reconstruction of past accrual/redemption calculations.
         */
        get: operations["listLoyaltyConfigHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/loyalty-config/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll back to a prior loyalty configuration version
         * @description Requires `loyalty_config.write`. Re-applies a past version's values as a new version (forward-only, like git revert) — history is never rewritten.
         */
        post: operations["rollbackLoyaltyConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a store's API keys
         * @description Requires `api_keys.read`. Never returns the key hash or plaintext.
         */
        get: operations["listStoreAPIKeys"];
        put?: never;
        /**
         * Create a new store API key
         * @description Requires `api_keys.rotate`. Returns the plaintext key exactly once — it is never persisted or logged again.
         */
        post: operations["createStoreAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/stores/{storeID}/api-keys/{keyID}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a store API key
         * @description Requires `api_keys.rotate`.
         */
        post: operations["revokeStoreAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{orgID}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent audit events for an Organization
         * @description Requires `audit.read`.
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable error message. */
            error: string;
            /** @description Machine-readable error code, present on a subset of error responses that callers may need to branch on programmatically (e.g. "daily_redeem_limit_exceeded", "qr_malformed", "over_refund"). Absent on errors with no defined code — callers must not assume this field is always present. */
            code?: string;
        };
        AuthTokens: {
            access_token?: string;
            /** Format: date-time */
            access_token_expires_at?: string;
            refresh_token?: string;
            /** Format: date-time */
            refresh_token_expires_at?: string;
            /** Format: int64 */
            customer_account_id?: number;
        };
        CustomerProfile: {
            /** Format: int64 */
            customer_account_id?: number;
            phone?: string;
            /** @enum {string} */
            status?: "active" | "blocked" | "deleted";
            /** Format: date-time */
            created_at?: string;
        };
        MeBalanceItem: {
            /** Format: int64 */
            store_id?: number;
            /** Format: int64 */
            client_id?: number;
            /** Format: int64 */
            balance?: number;
        };
        MeTransactionItem: {
            /** Format: int64 */
            store_id?: number;
            /** @description Merchant/store label. Empty if the store couldn't be resolved. */
            store_name?: string;
            /** Format: int64 */
            client_id?: number;
            /** @enum {string} */
            type?: "accrual" | "redeem" | "refund";
            /**
             * Format: decimal
             * @description Purchase amount this transaction is based on.
             */
            amount?: string;
            /** @example RUB */
            currency?: string;
            /** Format: int64 */
            points_delta?: number;
            /** Format: int64 */
            balance_after?: number;
            /**
             * Format: date-time
             * @description Operation date/time.
             */
            created_at?: string;
        };
        MeTransactionsPage: {
            transactions?: components["schemas"]["MeTransactionItem"][];
            /** @description Opaque; pass back as ?cursor= to fetch the next page. Omitted once history is exhausted. */
            next_cursor?: string;
        };
        AccrueRequest: {
            /** @description 1C's unique transaction identifier — the idempotency key together with (store, "accrual"). */
            transaction_id: string;
            /** @example +79261234567 */
            phone: string;
            /**
             * Format: decimal
             * @description Purchase amount, as a decimal string (not a float, to avoid precision loss).
             * @example 1250.00
             */
            amount: string;
        };
        TransactionResponse: {
            /** Format: int64 */
            client_id?: number;
            /** Format: int64 */
            points_earned?: number;
            /** Format: int64 */
            balance?: number;
            /** @description true if transaction_id was already processed and this is the original result, not a new accrual. */
            replayed?: boolean;
        };
        RedeemRequest: {
            transaction_id: string;
            /** Format: int64 */
            client_id: number;
            /** Format: int64 */
            points: number;
            /**
             * Format: decimal
             * @example 300.00
             */
            amount: string;
        };
        RedeemResponse: {
            /** Format: int64 */
            points_redeemed?: number;
            /** Format: int64 */
            balance?: number;
            replayed?: boolean;
        };
        ClientBalance: {
            /** Format: int64 */
            client_id?: number;
            /** Format: int64 */
            balance?: number;
        };
        RefundRequest: {
            /** @description 1C's unique identifier for this refund event — the idempotency key together with (store, "refund"). */
            transaction_id: string;
            /** @description external_tx_id of the accrual or redeem being reversed. */
            original_transaction_id: string;
            /**
             * @description Required only if original_transaction_id was used for both an accrual and a redeem under this store.
             * @enum {string}
             */
            original_transaction_type?: "accrual" | "redeem";
            /**
             * Format: decimal
             * @description This refund's amount (may be a partial refund); cumulative refunds against one original may never exceed its original amount.
             * @example 500.00
             */
            amount: string;
        };
        RefundResponse: {
            /** Format: int64 */
            client_id?: number;
            /** Format: int64 */
            points_reversed?: number;
            /**
             * Format: int64
             * @description May be negative if this refund reversed an accrual for more points than the client currently holds (DEC-012).
             */
            balance?: number;
            /**
             * Format: decimal
             * @description Cumulative amount refunded against the original transaction so far, including this refund.
             */
            refunded_amount_total?: string;
            fully_refunded?: boolean;
            replayed?: boolean;
        };
        IssueQRResponse: {
            /** @description Opaque, versioned, one-time-use token. Contains no PII. The mobile app renders this as a QR image — the backend never generates image data. */
            payload?: string;
            /** Format: date-time */
            expires_at?: string;
            /** @description Seconds until expiry, at response time. */
            expires_in?: number;
        };
        ResolveQRRequest: {
            payload: string;
        };
        ResolveQRResponse: {
            /** Format: int64 */
            client_id?: number;
            /** Format: int64 */
            balance?: number;
        };
        RegisterDeviceRequest: {
            /** @example android */
            platform: string;
            push_token: string;
        };
        RegisterDeviceResponse: {
            /** Format: int64 */
            device_id?: number;
        };
        Organization: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Store: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            organization_id?: number;
            name?: string;
        };
        /** @enum {string} */
        Role: "platform_admin" | "retailer_admin" | "store_manager" | "support_viewer";
        /** @enum {string} */
        StaffStatus: "active" | "disabled";
        StaffMembership: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            staff_user_id?: number;
            /** Format: int64 */
            organization_id?: number;
            /** Format: int64 */
            store_id?: number | null;
            role?: components["schemas"]["Role"];
            status?: components["schemas"]["StaffStatus"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** @description The target StaffUser's profile email. Empty until their first OIDC login. */
            email?: string;
            /** @description The target StaffUser's profile display name. Empty until their first OIDC login. */
            display_name?: string;
        };
        StaffMeMembership: {
            /** Format: int64 */
            organization_id?: number;
            /** Format: int64 */
            store_id?: number | null;
            role?: components["schemas"]["Role"];
            /** @description The permissions this membership's role grants (domain.RolePermissions), pre-resolved for the frontend. */
            permissions?: string[];
        };
        StaffMe: {
            /** Format: int64 */
            staff_user_id?: number;
            email?: string;
            display_name?: string;
            memberships?: components["schemas"]["StaffMeMembership"][];
        };
        AdminClient: {
            /** Format: int64 */
            client_id?: number;
            /** @description Masked (e.g. "********4567") if the caller's only membership in this scope is support_viewer. */
            phone?: string;
            /** Format: int64 */
            balance?: number;
        };
        AdminTransaction: {
            /** Format: int64 */
            id?: number;
            external_tx_id?: string;
            /** @enum {string} */
            type?: "accrual" | "redeem" | "refund";
            /** Format: int64 */
            points_delta?: number;
            /** Format: int64 */
            balance_after?: number;
            /** Format: date-time */
            created_at?: string;
        };
        LoyaltyConfig: {
            /** Format: int64 */
            readonly store_id?: number;
            /**
             * @description Selects the domain.Mechanic implementation to run on accrual. MVP only wires up "points".
             * @example points
             */
            mechanic: string;
            /**
             * Format: decimal
             * @description % of purchase amount credited as points.
             * @example 10
             */
            accrual_percent: string;
            /**
             * Format: decimal
             * @example 0
             */
            min_purchase_amount: string;
            /**
             * Format: int64
             * @example 0
             */
            min_balance_to_redeem: number;
            /**
             * Format: decimal
             * @example 100
             */
            max_redeem_percent: string;
            /**
             * Format: decimal
             * @example 1
             */
            points_exchange_rate: string;
            /**
             * Format: int64
             * @description Increments on every write. See /loyalty-config/history.
             */
            readonly version?: number;
        };
        LoyaltyConfigVersion: {
            /** Format: int64 */
            version: number;
            /** @example points */
            mechanic: string;
            /**
             * Format: decimal
             * @example 10
             */
            accrual_percent: string;
            /**
             * Format: decimal
             * @example 0
             */
            min_purchase_amount: string;
            /**
             * Format: int64
             * @example 0
             */
            min_balance_to_redeem: number;
            /**
             * Format: decimal
             * @example 100
             */
            max_redeem_percent: string;
            /**
             * Format: decimal
             * @example 1
             */
            points_exchange_rate: string;
            /** Format: int64 */
            changed_by_staff_user_id?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        APIKeyScope: "transactions.write" | "clients.lookup" | "balances.read";
        StoreAPIKey: {
            /** Format: int64 */
            id?: number;
            /** @description Non-secret, loggable prefix identifying the key — never the secret itself. */
            key_id?: string;
            name?: string;
            scopes?: components["schemas"]["APIKeyScope"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        StoreAPIKeyCreated: components["schemas"]["StoreAPIKey"] & {
            /** @description The actual API key. Returned exactly once, at creation — never persisted or logged, and never retrievable again. */
            plaintext_key?: string;
        };
        AuditEvent: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            occurred_at?: string;
            /** @enum {string} */
            actor_type?: "customer" | "staff" | "store_api_key" | "system";
            /** Format: int64 */
            actor_id?: number | null;
            action?: string;
            target_type?: string;
            /** Format: int64 */
            target_id?: number | null;
            metadata?: {
                [key: string]: unknown;
            };
            ip?: string;
        };
    };
    responses: {
        /** @description Malformed request body, path, or query parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or expired credential. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Credential valid but lacks the required scope/permission, or targets a resource outside its tenant. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource, or it doesn't belong to the caller's store/organization. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description transaction_id already used with different parameters (idempotency conflict), or a duplicate resource. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The referenced one-time resource is expired, already consumed, or never existed — deliberately a single response for all three (see DEC-011), so the caller can't distinguish them. */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A required backend (e.g. the rate limiter's Redis) is unreachable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        orgID: number;
        storeID: number;
    };
    requestBodies: never;
    headers: {
        /** @description Seconds until the caller may retry. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies are reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A dependency (Postgres or Redis) is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccrueRequest"];
            };
        };
        responses: {
            /** @description Accrual processed (or replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    redeemTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Redemption processed (or replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description client_id does not belong to this store. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["Conflict"];
            /** @description Insufficient balance to cover the requested redemption. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    refundTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundRequest"];
            };
        };
        responses: {
            /** @description Refund processed (or replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundResponse"];
                };
            };
            /** @description Malformed request, or original_transaction_type required to disambiguate (code "ambiguous_original_transaction"), or the original transaction is itself a refund (code "cannot_refund_refund"). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description original_transaction_id does not exist under this store. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["Conflict"];
            /** @description Refund amount exceeds the original's remaining refundable amount (code "over_refund"), or insufficient balance. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    resolveQR: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveQRRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveQRResponse"];
                };
            };
            /** @description Malformed payload (code "qr_malformed"). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            410: components["responses"]["Gone"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    lookupClientByPhone: {
        parameters: {
            query: {
                /** @example +79261234567 */
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientBalance"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getClientBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientBalance"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    requestOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example +79261234567 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description OTP sent (or would have been). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example sent */
                        status?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    verifyOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    /** @example 123456 */
                    code: string;
                    /** @description Required on first registration; omit on a returning login. */
                    consent_document_version?: string;
                    /** @example mobile_app */
                    consent_source?: string;
                };
            };
        };
        responses: {
            /** @description Verified — access/refresh token pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid or expired code. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Account blocked. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    refreshCustomerSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New token pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid, expired, or revoked session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    customerLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    customerLogoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMyBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        balances?: components["schemas"]["MeBalanceItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getMyTransactions: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque continuation token from a previous response's next_cursor. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeTransactionsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    issueQR: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueQRResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterDeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    staffOIDCLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id_token: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid ID token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Account disabled or no active organization membership. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getStaffMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organizations?: components["schemas"]["Organization"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        stores?: components["schemas"]["Store"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStaffMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        memberships?: components["schemas"]["StaffMembership"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createStaffMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    external_subject: string;
                    /** Format: int64 */
                    store_id?: number | null;
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMembership"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateStaffMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                membershipID: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    role?: components["schemas"]["Role"];
                    status?: components["schemas"]["StaffStatus"];
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    adminListClients: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clients?: components["schemas"]["AdminClient"][];
                        next_cursor?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    adminLookupClient: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    adminListClientTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
                clientID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transactions?: components["schemas"]["AdminTransaction"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getLoyaltyConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not configured yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    putLoyaltyConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoyaltyConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listLoyaltyConfigHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        history?: components["schemas"]["LoyaltyConfigVersion"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    rollbackLoyaltyConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    version: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Version not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStoreAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        api_keys?: components["schemas"]["StoreAPIKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createStoreAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    scopes: components["schemas"]["APIKeyScope"][];
                    /** Format: date-time */
                    expires_at?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreAPIKeyCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeStoreAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
                storeID: components["parameters"]["storeID"];
                keyID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["orgID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
